apiVersion: v1
kind: Service
metadata:
  name: rathena-server
  labels:
    app: rathena
spec:
  ports:
    - name: login
      protocol: TCP
      port: 6900
    - name: map
      protocol: TCP
      port: 5121
    - name: char
      protocol: TCP
      port: 6121
  selector:
    app: rathena
    component: server
    version: v1.0
  type: LoadBalancer
  loadBalancerIP: 52.232.25.13 # Previously provisioned Public IP in same resource group as cluster
  clusterIP: 10.0.0.3 # Default range: 10.0.0.0/16
---
apiVersion: v1
kind: Secret
metadata:
  name: rathena-server-pwd
  labels:
    app: rathena
type: Opaque
data:
  mysql-pwd: cDRzc0B3MHJkCg== # p4ss@w0rd in base64
  intersrv-passwd: cDRzc0B3MHJkCg== # p4ss@w0rd in base64