apiVersion: v1
kind: Secret
metadata:
  name: mysql-pwd
type: Opaque
data:
  password: cDRzc0B3MHJkCg== # p4ss@w0rd in base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rathena-mysql-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rathena-mysql
  labels:
    app: rathena
spec:
  ports:
    - protocol: TCP
      port: 3306
      name: mysql
  selector:
    app: rathena
    component: mysql
    version: v1.0
  clusterIP: 10.0.0.2 # Default range: 10.0.0.0/16
  loadBalancerIP: 52.232.26.187 # Previously provisioned Public IP in same resource group as cluster
  type: LoadBalancer
